baseurl = "https://48474.net/"
languageCode = "en-us"
title = "DenysG的个人博客"
theme = "angels-ladder"

[params]
    description = "DenysG'blog,技术博客,golang,hugo，没啥技术，没啥经验，没啥文笔，向往自由，不断折腾的技术男。"
    subtitle = "我必须承认，幸运喜欢照顾勇敢的人。---- 达尔文"
    github    = "https://github.com/cnphpbb/"
    copyright = "© 2018 135Get_Team. All rights reserved."
    dateFormat = "2006/01/02"
